title: Maryam Fattahi Vanani
description: Researcher in Distributed Systems, Blockchain, and Network Security
theme: jekyll-theme-minimal
<img src="assets/profile.jpg" alt="Maryam Fattahi Vanani" style="width: 600px; border-radius: 100%; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
